config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'links#new'
  get '/dashboard', to: 'pages#dashboard', as: 'admin'
  resources :links, only: %i[new create destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/link.rb
class Link < ApplicationRecord
  belongs_to :user
  validates :destination_url, presence: true
  validates_format_of :destination_url, with: /((?:https?\:\/\/|www\.)(?:[-a-z0-9]+\.)*[-a-z0-9]+.*)/i
  validates :title, length: { maximum: 10 }
  validates :short_url, presence: true, uniqueness: true

  def shorten_url
    slug = rand(36**8).to_s(36)
    slug = rand(36**8).to_s(36) while Link.where(short_url: slug).any?
    slug
  end

  def sanitize
    destination_url.strip!
    sanitize_url = destination_url.downcase.gsub(/(https?:\/\/)|(www\.)/,"")
    "http://#{sanitize_url}"
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :links, dependent: :destroy

  # format is handled by devise
  validates :email, presence: true, uniqueness: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/links_controller.rb
class LinksController < ApplicationController

  def new
    @link = Link.new
    @link.user = current_user
  end

  def create
    @link = Link.new(link_params)
    @link.user = current_user

    if @link.valid?
      @link.short_url = helpers.shorten(@link)
      @link.save!
      redirect_to root_path
    else
      flash[:error] = @link.errors.full_messages
      render 'new'
    end
  end

  def destroy
    @link = Link.find(params[:id])
    @link.destroy
    redirect_to admin_path
  end

  private

  def link_params
    params.require(:link).permit(:title, :destination_url, :short_url)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :authenticate_admin, only: :dashboard

  def dashboard
    @links = Link.all
  end

  def authenticate_admin
    redirect_to root_path unless current_user.admin
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/links_helper.rb
module LinksHelper

  def shorten(link)
    (link.title.blank? ? 'toon-link' : link.title) + "/#{link.shorten_url}"
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Shortener</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/links/new.html.erb
<div class="m-3">
  <h1>Toon Link</h1>
  <p>Turn big links into short links</p>
  <%= link_to "Log out", destroy_user_session_path, method: :delete, data: {turbo_method: :delete}  %>
</div>

<div class="d-flex flex-row justify-content-center m-3">
  <%= image_tag "link.jpeg", alt: "Link and toon link", width: 100%>
</div>
<div class="container d-flex flex-row justify-content-center">
  <div class="row col-6 p-3 shadow border justify-content-center">
    <%= simple_form_for (@link) do |f| %>
      <%= f.error_notification %>
      <%= f.input :destination_url, hint: 'Enter your url here', required: true, id: 'destination-url' %>
      <%= f.input :title,  hint: 'Provide a title if you want your short url to have a title' %>
      <%= f.submit class: 'btn btn-primary my-2'%>
    <% end %>
    <% if current_user.links.any? %>
      <p class="">Shortened link : <%= link_to current_user.links.last.short_url, "#{current_user.links.last.destination_url}" %></p>
      <p class='w-100 overflow-auto'>Original link : <%=  link_to current_user.links.last.destination_url %></p>
    <% end %>
  </div>
</div>

app/views/pages/dashboard.html.erb
<h1>Dashboard Admin </h1>
<%= link_to "Log out", destroy_user_session_path, method: :delete, data: {turbo_method: :delete}  %>
<%= image_tag "ganondorf.jpeg", alt: "ganondorf", width: 100, height: 100%>
<div class="container">
  <div class="d-flex flex-row justify-content-start m-3 bg-light overflow-hidden border">
    <table class="w-100">
      <thead>
        <tr>
          <th class='p-1'>Action</th>
          <th class='p-1'>Short Link</th>
          <th class='p-1'>User</th>
          <th class='p-1'>Original link</th>
        </tr>
      </thead>
      <tbody>
        <% @links.each do |link| %>
          <tr>
            <td class='p-1'><%= link_to "Delete", link_path(link), method: :delete, data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} %></td>
            <td class='p-1'><%= link_to link.short_url, link.destination_url %></td>
            <td class='p-1'><%= link.user.email %></td>
            <td class='p-1'><%= link.destination_url %></td>
          </tr>
        <% end %>
      </tbody>
    </table>


  </div>
</div>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>
<div class="d-flex border bg-dark w-100"></div>